name: Deploy Worker with Durable Object
on:
  push:
    branches:
      - main
env:
  USERNAME: ${{ vars.USERNAME }}
  PASSWORD: ${{ vars.PASSWORD }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Print env variables
        run: printenv
        shell: bash
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.55.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
